FROM ubuntu:14.04

MAINTAINER Andrea Grandi <andrea@thisisglow.com>

# Create the MongoDB data directory
RUN mkdir -p /data/db

# Create the PostgreSQL data directory
RUN mkdir -p /var/lib/postgresql
